- name: Add Grafana repository file [RHEL/CentOS]
  template:
    src: grafana.repo.j2
    dest: "/etc/yum.repos.d/grafana.repo"
    force: true
    backup: true

- name: Install Grafana
  yum:
    name: grafana
    state: latest
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2
  notify: restart grafana
