prometheus_db_dir: /var/lib/prometheus
prometheus_config_dir: /etc/prometheus

prometheus_version: 2.17.1

prometheus_binary_local_dir: ''

prometheus_storage_retention: "30d"

prometheus_storage_retention_size: "0"

prometheus_web_listen_address: "0.0.0.0:9090"

prometheus_web_external_url: ''

prometheus_config_flags_extra: {}

prometheus_config_file: 'prometheus.yml.j2'

prometheus_global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

prometheus_external_labels:
  environment: "{{ ansible_fqdn | default(ansible_host) | default(inventory_hostname) }}"

prometheus_remote_write: []

prometheus_remote_read: []

prometheus_alertmanager_config: []

prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  - job_name: "node"
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/node.yml"
