---
grafana_version: latest

grafana_instance: "{{ ansible_fqdn | default(ansible_host) | default(inventory_hostname) }}"

grafana_logs_dir: "/var/log/grafana"
grafana_data_dir: "/var/lib/grafana"

grafana_domain: "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}"

grafana_dashboards_dir: "dashboards"

grafana_plugins: []
#  - raintank-worldping-app
